import os

BASE_DIR = os.path.abspath(os.path.dirname(__file__))
UPLOAD_FOLDER = os.path.join(BASE_DIR, "uploads")
MAX_CONTENT_LENGTH = 20 * 1024 * 1024  # 20MB

'''
1 - Se o arquivo de origem for excel, lembrar de sempre alterar o nome da sheet para "base"
2 - PK_ORIGEM é a coluna com identificador único, Ex: Matricula, cpf, CR, etc...
3 - hash_columns deve ser o mesmo nome na tabela destino e não do arquivo
'''

SERVERS = {
    "servidor_x": {
        "driver": "{ODBC Driver 17 for SQL Server}",
        "server": "Primno3",
        "database": "Qualidade_HUB_Correlacao",
        "trusted_connection": "yes",
    },
    "servidor_cx": {
        "driver": "{ODBC Driver 17 for SQL Server}",
        "server": "Primno3",
        "database": "DIRETORIA_CX",
        "trusted_connection": "yes",
    },
    "servidor_y": {
        "driver": "{ODBC Driver 17 for SQL Server}",
        "server": "Primno",
        "database": "DATABASE_Y",
        "trusted_connection": "yes",
    },
}

DB_CONFIG = {
    "log_table": "dbo.LOG_IMPORTADOR",
    "log_server": "servidor_x",
}

DATASET_CONFIG = {
    "VALIDADOS_CALLSENSE_MD": {
        "label": "VALIDADOS CALLSENSE",
        "server": "servidor_x",
        "table": "silver.VALIDADOS_CALLSENSE_MD",
        "pk_origem": "id_atendimento",
        "columns": {"DATA RECEBIMENTO": "data_recebimento",
                    "DATA ENVIO": "data_envio",
                    "DATA RETORNO": "data_retorno",
                    "IdAtendimento": "id_atendimento",
                    "DataHora": "data_hora",
                    "IdOperacao": "id_operacao",
                    "Matricula": "matricula",
                    "resumo_geral": "resumo_geral",
                    "nivel_destrato": "nivel_destrato",
                    "score_destrato": "score_destrato",
                    "aspectos.destrato.status": "aspectos_destrato_status",
                    "aspectos.destrato.gravidade": "aspectos_destrato_gravidade",
                    "aspectos.destrato.evidencias": "aspectos_destrato_evidencias",
                    "Início Monitoria Qualidade": "inicio_monitoria_qualidade",
                    "Qualidade do Áudio (Qualidade - Audio)": "qualidade_audio",
                    "O Destrato transcrito foi confirmado no áudio?": "destrato_confirmado_audio",
                    "Foi o mesmo apontado pela IA?": "apontado_pela_ia",
                    "Caso áudio não encontrado, explique por que não foi possível encontrar. (Qualidade - Audio)": "motivo_audio_nao_encontrado",
                    "Houve destrato do operador ao cliente e ouvido pelo cliente? (Qualidade - Audio)": "destrato_ouvido_cliente",
                    "Qual foi o tipo de destrato? (Qualidade - Audio)": "tipo_destrato",
                    "Qual a gravidade do destrato? (Qualidade - Audio)": "gravidade_destrato",
                    "O destrado apontado é importante para a Qualidade? Ou seja, devemos continuar apontando esse tipo? (Qualidade - Audio)": "destrato_importante_qualidade",
                    "No caso em que não houve destrato, nos ajude a diagnosticar por que a IA errou (Qualidade - Audio)": "diagnostico_erro_ia",
                    "Considerações finais (No caso de destrato, dê detalhes sobre o destrato cometido. No caso de não destrato, explique por que a IA errou.) (Qualidade - Audio)": "consideracoes_finais",
        },
        "hash_columns": ["resumo_geral", "nivel_destrato", "score_destrato", "aspectos_destrato_status"],
        "usar_scd2": True,
        "delete_historico": False,
        "coluna_data": "",
    },

    "DIM_CR": {
        "label": "DIM CR",
        "server": "servidor_cx",
        "table": "HUB_ESTRUTURANTE.DIM_CR_COMPLETA",
        "pk_origem": "CR_FuncionarioRM",
        "columns": {
                    "CR_FuncionarioRM": "CR_FUNCIONARIORM",
                    "NOME_CR": "NOME_CR",
                    "STATUS": "STATUS",
                    "CLIENTE": "CLIENTE",
                    "CONTRATO": "CONTRATO",
                    "INDUSTRIAS": "INDUSTRIAS",
                    "NÚCLEO": "NÚCLEO",
                    "DIRETOR": "DIRETOR",
                    "HEAD QUALIDADE": "HEAD_QUALIDADE",
                    "GERENTE QUALIDADE": "GERENTE_QUALIDADE",
                    "EXECUTIVO OPERACIONAL": "EXECUTIVO_OPERACIONAL",
                    "GERENTE OPERACIONAL": "GERENTE_OPERACIONAL",
                    "UNIDADE": "UNIDADE",
                    "CIDADE": "CIDADE",
                    "CR": "CR",
                    "VP": "VP",
                    "VP_NEW": "VP_NEW",
                    "DIRETOR_NEW": "DIRETOR_NEW",
                    "CIDADE_NEW": "CIDADE_NEW",
                    "EX": "EX",
                    "COORDENADOR (HOMINUM)": "COORDENADOR_HOMINUM",
                    "TIPO DE LOGO": "TIPO_DE_LOGO",
                    "CLIENTE FIN": "CLIENTE_FIN"
                    },
        "hash_columns": ["STATUS", "CLIENTE", "CONTRATO", "DIRETOR", "HEAD_QUALIDADE",
                         "GERENTE_QUALIDADE", "EXECUTIVO_OPERACIONAL", "GERENTE_OPERACIONAL",
                         "VP", "UNIDADE", "CIDADE", "COORDENADOR_HOMINUM", "TIPO_DE_LOGO", "CLIENTE_FIN"],
        "usar_scd2": True,
        "delete_historico": False,
        "coluna_data": "",
        "colunas_decimais": "",
        "colunas_texto": [],
        "transform": "",
        "extra_sql": "update_dim_cr",
    },

    "ESTRUTURANTE_BASE_FINANCEIRO": {
        "label": "BASE FINANCEIRO",
        "server": "servidor_x",
        "table": "HUB.ESTRUTURANTE_BASE_FINANCEIRO_IMPORT",
        "pk_origem": "",
        "columns": {
                    "Ano": "Ano",
                    "Mes": "Mes",
                    "CR": "CR",
                    "CR_Unificado": "CR_Unificado",
                    "Cliente": "Cliente",
                    "Operacao": "Operacao",
                    "Gerente": "Gerente",
                    "Nome_CR": "Nome_CR",
                    "Unidade": "Unidade",
                    "Agrupamento": "Agrupamento",
                    "Agrupamento2": "Agrupamento2",
                    "OperacaoHomunim": "OperacaoHomunim",
                    "Modelo": "Modelo",
                    "Executivo": "Executivo",
                    "TipoFaturamento": "TipoFaturamento",
                    "CoordenadorPlanejamento": "CoordenadorPlanejamento",
                    "AnalistaResponsavel": "AnalistaResponsavel",
                    "Situacao": "Situacao",
                    "Site": "Site",
                    "Area": "Area",
                    "Vertical": "Vertical",
                    "TipoAtendimento": "TipoAtendimento",
                    "Conta": "Conta",
                    "tipo": "tipo",
                    "Trabalho": "Trabalho",
                    "TrabalhoDetalhado": "TrabalhoDetalhado",
                    "Dre": "Dre",
                    "Premissa": "Premissa",
                    "OrçadoAnterior": "OrcadoAnterior",
                    "OrçadoAnterior + 1": "OrcadoAnterior + 1",
                    "OrçadoAtual": "OrcadoAtual",
                    "OrçadoAtual + 1": "OrcadoAtual + 1",
                    "Real0": "Real0",
                    "Real-1": "Real-1",
                    "Plano0": "Plano0",
                    "Plano + 1": "Plano + 1",
                    "1ª - Projecao": "1ª - Projecao",
                    "2ª - Projecao": "2ª - Projecao",
                    "3ª - Projecao": "3ª - Projecao",
                    "ProjecaoAtual": "ProjecaoAtual",
                    "4ª - Projecao": "4ª - Projecao",
                    "VicePresidente": "VP",
                    "Diretor": "DIRETOR"
        },
        "hash_columns": [],
        "usar_scd2": False,
        "delete_historico": True,
        "coluna_data": "",
        "colunas_decimais": [
            "OrcadoAtual",
            "OrcadoAtual + 1",
            "Real0",
            "Real-1",
            "Plano0",
            "Plano + 1",
            "1ª - Projecao",
            "2ª - Projecao",
            "3ª - Projecao",
            "ProjecaoAtual",
            "4ª - Projecao"
        ],
        "colunas_texto": [],
        "transform": "_TRATATIVAS_FINANCEIRO",
        "extra_sql": "",
    },

    "RECLAME_AQUI_LIGHT": {
        "label": "RECLAME AQUI - LIGHT",
        "server": "servidor_x",
        "table": "HUB.RECLAME_AQUI_TESTE",
        "pk_origem": "",
        "columns": {"Id HugMe": "Id_HugMe",
            "Origem": "Origem",
            "Id Origem": "Id_Origem",
            "Data Reclamação": "Data_Reclamacao",
            "Status Hugme": "Status_Hugme",
            "Status RA": "Status_RA",
            "Arquivado ?": "Arquivado_",
            "Título": "Titulo",
            "Texto da Reclamação": "Texto_da_Reclamacao",
            "Data Avaliacao": "Data_Avaliacao",
            "Motivo da Reclamação RA": "Motivo_da_Reclamacao_RA",
            "Sentimento RA*": "Sentimento_RA",
            "Nome": "Nome",
            "Nome social do consumidor": "Nome_social_do_consumidor",
            "RG": "RG",
            "CPF/CNPJ": "CPF_CNPJ",
            "Pessoa Física ou Jurídica?": "Pessoa_Fisica_ou_Juridica",
            "Email": "Email",
            "Telefones": "Telefones",
            "Cidade": "Cidade",
            "Estado": "Estado",
            "Quantidade de Tags": "Quantidade_de_Tags",
            "Tags": "Tags",
            "Resposta da empresa": "Resposta_da_empresa",
            "Data de Resposta": "Data_de_Resposta",
            "Interações neste ticket": "Interacoes_neste_ticket",
            "Réplicas na reclamação RA": "Replicas_na_reclamacao_RA",
            "Seu problema foi resolvido?": "Seu_problema_foi_resolvido",
            "Voltaria a fazer negócio?": "Voltaria_a_fazer_negocio",
            "Nota": "Nota",
            "Consideração Consumidor": "Consideracao_Consumidor",
            "Data Consideração Consumidor": "Data_Consideracao_Consumidor",
            "Consideração Empresa": "Consideracao_Empresa",
            "Data Consideração Empresa": "Data_Consideracao_Empresa",
            "Tempo primeira resposta (privado)": "Tempo_primeira_resposta_privado",
            "Tempo primeira resposta (público)": "Tempo_primeira_resposta_publico",
            "Tempo Avaliação": "Tempo_Avaliacao",
            "Comentários na reclamação*": "Comentarios_na_reclamacao",
            "Atribuido Para": "Atribuido_Para",
            "Quantidade de Atribuições": "Quantidade_de_Atribuicoes",
            "Redistribuições": "Redistribuicoes",
            "Moderações neste ticket": "Moderacoes_neste_ticket",
            "Mensagens internas neste ticket": "Mensagens_internas_neste_ticket",
            "Quantidade de lembretes": "Quantidade_de_lembretes",
            "Data última réplica": "Data_ultima_replica",
            "Data da última modificação": "Data_da_ultima_modificacao",
            "Avaliacao Favoravel": "Avaliacao_Favoravel",
            "Origem RA": "Origem_RA",
            "Data de Desativação RA": "Data_de_Desativacao_RA",
            "Motivo de Desativação RA": "Motivo_de_Desativacao_RA",
            "Avaliações desconsideradas RA": "Avaliacoes_desconsideradas_RA",
            "Blackfriday RA": "Blackfriday_RA",
            "Sentimento": "Sentimento",
            "Lembretes": "Lembretes",
            "Dados Complementares Consumidor": "Dados_Complementares_Consumidor",
            "Avaliado sem resposta RA": "Avaliado_sem_resposta_RA",
            "Moderação status": "Moderacao_status",
            "Moderação motivo": "Moderacao_motivo",
            "Moderação data de solicitação": "Moderacao_data_de_solicitacao",
            "Moderação usuário que solicitou": "Moderacao_usuario_que_solicitou",
            "Moderação data da resposta": "Moderacao_data_da_resposta",
            "Tipo Hugme": "Tipo_Hugme",
            "Data fechamento": "Data_fechamento",
            "Quantidade interações consumidor": "Quantidade_interacoes_consumidor",
            "Quantidade interações empresa": "Quantidade_interacoes_empresa",
            "Feed tipo": "Feed_tipo",
            "Fonte informação tipo": "Fonte_informacao_tipo",
            "Histórico": "Historico",
            "Canal": "Canal",
            "RA Prime": "RA_Prime",
            "ID Reclame Aqui": "ID_Reclame_Aqui",
            "Última interação na mensagem privada": "Ultima_interacao_na_mensagem_privada",
            "Recebeu avaliação por WhatsApp": "Recebeu_avaliacao_por_WhatsApp",
            "Avaliou por WhatsApp": "Avaliou_por_WhatsApp",
            "Categoria RA": "Categoria_RA",
            "Problema RA": "Problema_RA",
            "Produto RA": "Produto_RA"
        },
        "hash_columns": [],
        "usar_scd2": False,
        "delete_historico": True,
        "coluna_data": "Data_Reclamacao",
        "colunas_decimais": "",
        "colunas_texto": [],
        "transform": "",
        "extra_sql": "",
    },

    "INTERACOES_LIGHT": {
        "label": "Interações - LIGHT",
        "server": "servidor_x",
        "table": "HUB.interacoes_TESTE",
        "pk_origem": "",
        "columns": {"conversation_id": "conversation_id",
                "session_id": "session_id",
                "conversation_start": "conversation_start",
                "conversation_end": "conversation_end",
                "segment_start": "segment_start",
                "segment_end": "segment_end",
                "participant_id": "participant_id",
                "participant_name": "participant_name",
                "user_id": "user_id",
                "purpose": "purpose",
                "direction": "direction",
                "media_type": "media_type",
                "disconnect_type": "disconnect_type",
                "queue_id": "queue_id",
                "wrap_up_code": "wrap_up_code",
                "alert": "alert",
                "interact": "interact",
                "voicemail": "voicemail",
                "wrapup": "wrapup",
                "total": "total",
                "ani": "ani",
                "dnis": "dnis",
                "_sdc_sequence": "_sdc_sequence",
                "_sdc_table_version": "_sdc_table_version",
                "_sdc_batched_at": "_sdc_batched_at",
                "sip_response_codes": "sip_response_codes",
                "id": "id",
                "external_tag": "external_tag",
                "nome": "nome",
                "username": "username",
                "nota_pergunta": "nota_pergunta",
                "resolveu_problema": "resolveu_problema",
                "silence_ms": "silence_ms",
                "silence_pct": "silence_pct",
                "fila": "fila"
        },
        "hash_columns": [],
        "usar_scd2": False,
        "delete_historico": True,
        "coluna_data": "conversation_start",
        "colunas_decimais": "",
        "colunas_texto": ["alert", "interact", "total", "silence_ms", "silence_pct"],
        "transform": "",
        "extra_sql": "",
    },
}